baseURL = "02infinite.vercel.app/"
languageCode = "zh-cn"
title = "jokereven(å‘¨é–)"
theme = "github-style"

[params]
  author = "ZHOUJING"
  description = "You gotta win once in your life."
  github = "jokereven"
  twitter = "cnzjing125"
  # linkedin = "jokereven"
  # instagram = "jokereven"
  # tumblr = "jokereven"
  email = "zjing125.cn@gmail.com"
  url = "blog.code520.com.cn"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  favicon = "/images/github.png"
  location = "Wuhan, China"
  userStatusEmoji = "ğŸ˜€"
  enableGitalk = true

  [params.gitalk]
    clientID = "8b53e24183ead47205c5" # Your client ID
    clientSecret = "160dae42f5ab06f36e57b525a1920d519f802844" # Your client secret
    repo = "02infinite" # æ‚¨çš„åšå®¢çš„githubåœ°å€Repository name
    owner = "jokereven" # æ‚¨çš„GitHub ID
    admin = ["jokereven"] # æ‚¨çš„GitHub ID
    id = "location.pathname" # æ–‡ç« é¡µé¢çš„é“¾æ¥åœ°å€å°±æ˜¯ID
    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage = 15 # Pagination size, with maximum 100.
    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually = true # è®¾ç½®ä¸ºtrueï¼Œå¦‚æœæ˜¯ç®¡ç†å‘˜ç™»å½•ï¼Œä¼šè‡ªåŠ¨åˆ›å»ºissueï¼Œå¦‚æœæ˜¯falseï¼Œéœ€è¦ç®¡ç†å‘˜æ‰‹åŠ¨æ·»åŠ ç¬¬ä¸€ä¸ªè¯„è®º(issue)
    distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.
    proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token" # å¯ä»¥è‡ªè¡Œæ·»åŠ åå‘ä»£ç†

  [[params.links]]
    title = "Link2"
    href = "https://blog.code520.com.cn"
    icon = "https://blog.code520.com.cn/medias/detail/logo.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
